# Generated by Django 4.2.11 on 2024-04-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_profile_latest_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='docking',
            name='pockets',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
