# Generated by Django 4.2.11 on 2024-05-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_docking_pockets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligand',
            name='ligand_name',
            field=models.CharField(default='ligand', max_length=50),
        ),
        migrations.AlterField(
            model_name='protein',
            name='protein_name',
            field=models.CharField(default='protein', max_length=50),
        ),
    ]
